language: c
compiler:
    - gcc
    - clang
before_install:
    - sudo add-apt-repository "deb mirror://mirrors.ubuntu.com/mirrors.txt trusty main restricted universe multiverse" -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq gtk-doc-tools libgnutls-dev libgsasl7-dev libxml2-dev libglib2.0-dev libgtk-3-dev libavahi-client-dev libdaemon-dev libpam-dev gobject-introspection
script: ./autogen.sh --with-gtk3 --with-infgtk --with-inftextgtk --with-avahi --with-libdaemon --enable-gtk-doc && make && make check
